In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

1.12.0


In [5]:
hello = tf.constant("Hello ")

In [6]:
world = tf.constant(" Wolrd")

In [7]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [8]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [12]:
with tf.Session() as sess:
    print(sess.run(hello+world))

b'Hello  Wolrd'


In [13]:
a = tf.constant(10)

In [14]:
b = tf.constant(4)

In [15]:
sess = tf.InteractiveSession()

In [16]:
print(sess.run(a+b))

14


In [17]:
const = tf.constant(10)

In [18]:
fill_mat = tf.fill((4,4),10)

In [19]:
myzeros = tf.zeros((4,4))

In [20]:
myones = tf.ones((4,4))

In [22]:
myrandn = tf.random_normal((4,4))

In [23]:
myrandu = tf.random_uniform((4,4), minval=1, maxval=10)

In [24]:
operations = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [25]:
for op in operations:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-1.8699179   0.19525336  1.3558111   0.03870289]
 [ 1.1854964  -0.7583318   1.3117244  -0.5158926 ]
 [-0.39281     0.27532795  0.35792127 -0.7380673 ]
 [-0.29606852  1.4399695   1.0650479   1.0249228 ]]


[[7.610012  5.4338913 6.819313  9.284353 ]
 [1.0843415 9.024801  8.442123  1.3309739]
 [2.4476495 7.39571   7.918519  9.722907 ]
 [1.3463515 2.1305726 6.843069  2.7024765]]




In [26]:
a = tf.constant([ [10,5],
                  [20,5]])

In [28]:
b = tf.constant([[10], [100]])

In [30]:
result = tf.matmul(a,b)

In [31]:
result.eval()

array([[600],
       [700]])